import * as THREE from "https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js";
const mobile=matchMedia("(max-width:700px)").matches, scene=new THREE.Scene();
scene.background=new THREE.Color(0x8fc8ef);scene.fog=new THREE.Fog(0x8fc8ef,18,70);
const camera=new THREE.PerspectiveCamera(72,innerWidth/innerHeight,.05,140);
const renderer=new THREE.WebGLRenderer({antialias:!mobile,powerPreference:"high-performance"});
renderer.setPixelRatio(Math.min(devicePixelRatio,mobile?1.35:2));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=!mobile;document.getElementById("game").appendChild(renderer.domElement);
const sun=new THREE.DirectionalLight(0xfff3d0,2.2);sun.position.set(25,35,15);sun.castShadow=!mobile;if(!mobile)sun.shadow.mapSize.set(1024,1024);scene.add(sun,new THREE.HemisphereLight(0xbde4ff,0x35402d,1.1));
const mats={grass:new THREE.MeshLambertMaterial({color:0x62a84e}),dirt:new THREE.MeshLambertMaterial({color:0x7d5335}),stone:new THREE.MeshLambertMaterial({color:0x81898b}),wood:new THREE.MeshLambertMaterial({color:0x8c633e}),leaves:new THREE.MeshLambertMaterial({color:0x3f8f45,transparent:true,opacity:.92}),sand:new THREE.MeshLambertMaterial({color:0xd5bd78}),water:new THREE.MeshLambertMaterial({color:0x3e9dd1,transparent:true,opacity:.65})};
const blocks=["grass","dirt","stone","wood","leaves","sand","water"],icons={grass:"🌿",dirt:"🟫",stone:"⬜",wood:"🪵",leaves:"🍃",sand:"🟨",water:"💧"},geo=new THREE.BoxGeometry(1,1,1),world=new Map();let selected=0;
const key=(x,y,z)=>x+","+y+","+z;function put(x,y,z,type){const k=key(x,y,z);if(world.has(k))return;const m=new THREE.Mesh(geo,mats[type]);m.position.set(x+.5,y+.5,z+.5);m.castShadow=!mobile;m.receiveShadow=true;m.userData={x,y,z,type};scene.add(m);world.set(k,m)}
function remove(x,y,z){const k=key(x,y,z),m=world.get(k);if(m){scene.remove(m);world.delete(k)}}
function h(x,z){return Math.max(1,Math.floor(3+Math.sin(x*.33)*1.3+Math.cos(z*.27)*1.1+Math.sin((x+z)*.14)))}
for(let x=-22;x<22;x++)for(let z=-22;z<22;z++){let y0=h(x,z);for(let y=0;y<=y0;y++)put(x,y,z,y===y0?"grass":y>y0-3?"dirt":"stone")}
for(let x=-18;x<18;x+=5)for(let z=-18;z<18;z+=6){let y0=h(x,z);if(Math.abs(x)+Math.abs(z)<7)continue;for(let y=1;y<4;y++)put(x,y0+y,z,"wood");for(let dx=-2;dx<=2;dx++)for(let dz=-2;dz<=2;dz++)for(let dy=3;dy<=4;dy++)if(Math.abs(dx)+Math.abs(dz)<4)put(x+dx,y0+dy,z+dz,"leaves")}
for(let x=-20;x<-13;x++)for(let z=8;z<20;z++)put(x,2,z,"water");
document.getElementById("blockCount").textContent=world.size;
const player={x:0,y:h(0,0)+1.05,z:6};let yaw=0,pitch=0,vy=0,onGround=false;camera.position.set(player.x,player.y+1.55,player.z);
const keys=new Set();addEventListener("keydown",e=>{keys.add(e.code);if(e.code.startsWith("Digit"))select(+e.code.slice(5)-1);if(e.code==="KeyQ")breakTarget();if(e.code==="KeyE")placeTarget()});addEventListener("keyup",e=>keys.delete(e.code));
const hot=document.getElementById("hotbar");blocks.forEach((b,i)=>{let d=document.createElement("button");d.className="slot";d.innerHTML="<span>"+icons[b]+"</span><em>"+(i+1)+"</em>";d.onclick=()=>select(i);hot.appendChild(d)});function select(i){if(i<0||i>=blocks.length)return;selected=i;document.querySelectorAll(".slot").forEach((e,n)=>e.classList.toggle("active",n===i))}select(0);
let locked=false;document.getElementById("play").onclick=()=>{document.getElementById("start").classList.add("hidden");if(!mobile)renderer.domElement.requestPointerLock()};document.addEventListener("pointerlockchange",()=>locked=document.pointerLockElement===renderer.domElement);document.addEventListener("mousemove",e=>{if(!locked)return;yaw-=e.movementX*.0022;pitch-=e.movementY*.0022;pitch=Math.max(-1.45,Math.min(1.45,pitch))});
function ray(){let r=new THREE.Raycaster();r.setFromCamera({x:0,y:0},camera);return r.intersectObjects([...world.values()])[0]}function breakTarget(){let q=ray();if(q){let p=q.object.userData;remove(p.x,p.y,p.z);document.getElementById("blockCount").textContent=world.size}}function placeTarget(){let q=ray();if(!q)return;let p=q.object.userData,n=q.face.normal,x=p.x+n.x,y=p.y+n.y,z=p.z+n.z;if(y>=0&&!world.has(key(x,y,z))){put(x,y,z,blocks[selected]);document.getElementById("blockCount").textContent=world.size}}
renderer.domElement.onmousedown=e=>{if((locked||mobile)&&e.button===0)breakTarget();if((locked||mobile)&&e.button===2)placeTarget()};renderer.domElement.oncontextmenu=e=>e.preventDefault();
let sx=0,sz=0,drag=false;const stick=document.getElementById("stick");stick.onpointerdown=e=>{drag=true;stick.setPointerCapture(e.pointerId)};stick.onpointermove=e=>{if(!drag)return;let r=stick.getBoundingClientRect();sx=Math.max(-1,Math.min(1,(e.clientX-r.left-r.width/2)/35));sz=Math.max(-1,Math.min(1,(e.clientY-r.top-r.height/2)/35));stick.querySelector("i").style.transform="translate("+sx*25+"px,"+sz*25+"px)"};stick.onpointerup=()=>{drag=false;sx=sz=0;stick.querySelector("i").style.transform=""};document.getElementById("jumpBtn").onclick=()=>{if(onGround)vy=.19};document.getElementById("breakBtn").onclick=breakTarget;document.getElementById("placeBtn").onclick=placeTarget;
function update(dt){let f=(keys.has("KeyW")?1:0)-(keys.has("KeyS")?1:0)-sz,s=(keys.has("KeyD")?1:0)-(keys.has("KeyA")?1:0)+sx,sp=(keys.has("ShiftLeft")?7:4.2)*dt;player.x+=(Math.sin(yaw)*f+Math.cos(yaw)*s)*sp;player.z+=(Math.cos(yaw)*f-Math.sin(yaw)*s)*sp;vy-=.011;player.y+=vy;let floor=h(Math.floor(player.x),Math.floor(player.z))+1.05;if(player.y<=floor){player.y=floor;vy=0;onGround=true}else onGround=false;if(keys.has("Space")&&onGround)vy=.19;camera.position.set(player.x,player.y+1.55,player.z);camera.rotation.set(pitch,yaw,0,"YXZ")}
let last=performance.now(),frames=0,ft=last;function loop(now){requestAnimationFrame(loop);let dt=Math.min(.033,(now-last)/1000);last=now;update(dt);sun.position.x=Math.sin(now*.00003)*35;sun.position.z=Math.cos(now*.00003)*35;renderer.render(scene,camera);frames++;if(now-ft>500){document.getElementById("fps").textContent=Math.round(frames*1000/(now-ft))+" FPS";frames=0;ft=now}document.getElementById("coords").textContent=Math.floor(player.x)+","+Math.floor(player.y)+","+Math.floor(player.z)}loop(performance.now());
document.getElementById("debugBtn").onclick=()=>document.getElementById("debug").classList.toggle("hidden");addEventListener("resize",()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,mobile?1.35:2))});